<?php

define("SITE_ROOT", dirname(__FILE__) . DIRECTORY_SEPARATOR);
define("INCL_ROOT", SITE_ROOT . "incl" . DIRECTORY_SEPARATOR);
define("ASSETS_ROOT", SITE_ROOT . "assets" . DIRECTORY_SEPARATOR);
define("ADMIN_ROOT", SITE_ROOT . "admin" . DIRECTORY_SEPARATOR);
define("CMS_ROOT", SITE_ROOT . "cms" . DIRECTORY_SEPARATOR);
define("IMG_ROOT", SITE_ROOT . "img" . DIRECTORY_SEPARATOR);

?>