INSERT INTO category (cat_name, parent_id) VALUES 
("Electronics & Computers" , NULL),
("Movies, TV & Music", NULL),
("Home, Garden & DIY", NULL),
("Toys, Children & Baby", NULL),
("Clothes, Shoes & Jewellery", NULL),
("Sports & Outdoors", NULL),
("Health & Beauty", NULL),
("Car & Motorbike", NULL),
("Books", NULL),
("Electronics", 1), 
("Computers", 1),
("Music", 2),
("Musical Instruments", 2),
("Film", 2),
("TV", 2),
("Garden & Outdoors", 3),
("Homeware & Furniture", 3),
("Kitchen & Dining", 3),
("Home Appliances", 3),
("Lighting", 3),
("Toys & Games", 4),
("Baby", 4),
("Clothing", 5),
("Shoes", 5),
("Jewellery", 5),
("Watches", 5),
("Handbags & Shoulder Bags", 5),
("Luggage", 5),
("Fitness", 6),
("Camping & Hiking", 6),
("Cycling", 6),
("Athletics", 6),
("Winter Sports", 6),
("Golf", 6),
("Water Sports", 6),
("Beauty", 7),
("Health & Personal Care", 7),
("Car Accessories & Parts", 8),
("Tools & Equipment", 8),
("Sat Nav & Car Electronics", 8),
("Motorbike Accessories & Parts", 8),
("Paperbacks", 9),
("Hardbacks", 9),
("Textbooks", 9),
("Audiobooks", 9),
("Camera & Photo", 10), ("TV & Home Cinema", 10), ("Audio & HiFi", 10), ("Phones", 10), ("Sat Nav & Car Electronics", 10), ("Electronics Accessories", 10), ("PC & Video Games", 10),
("Laptops", 11), ("Tablets", 11), ("Computer Accessories", 11), ("Computer Components", 11), ("Software", 11), ("Printers & Ink", 11),
("Beautiful South", 12), ("Fleetwood Mac", 12), ("The Manic Street Preachers", 12), ("Manu Chao", 12), ("Dire Straits", 12), ("Alkaline Trio", 12), ("Arcade Fire", 12), ("Bob Dylan", 12),("Guns n' Roses", 12),
("Guitars", 13), ("Pianos & Keyboards", 13), ("Drums & Percussion", 13), ("Band & Orchestra", 13),
("Action", 14), ("Adventure", 14), ("Animation", 14), ("Biography", 14), ("Comedy", 14), ("Crime", 14), ("Documentary", 14), ("Drama", 14), ("Family", 14), ("Fantasy", 14), ("Film Noir", 14), ("History", 14), ("SciFi", 14),
("Action", 15), ("Adventure", 15), ("Animation", 15), ("Biography", 15), ("Comedy", 15), ("Crime", 15), ("Documentary", 15), ("Drama", 15), ("Family", 15), ("Fantasy", 15), ("Film Noir", 15), ("History", 15), ("SciFi", 15),
("Mens", 23), ("Womens", 23), ("Boys", 23), ("Girls", 23),
("Animals", NULL), ("Cats", 102);

INSERT INTO product (p_name, p_long_desc, p_price, p_stock_quantity, p_photo_url) VALUES
("A Computer", "Uber fast computer", 1234.56,5,"ubfastcomp.jpg"),
("A Cat", "A cute kitten", 25.00, 1, "cutekitten.jpg"),
("Mythical Man Month", "Few books on software project management have been as influential and timeless as The Mythical Man-Month. With a blend of software engineering facts and thought-provoking opinions, Fred Brooks offers insight for anyone managing complex projects. These essays draw from his experience as project manager for the IBM System/360 computer family and then for OS/360, its massive software system. Now, 20 years after the initial publication of his book, Brooks has revisited his original ideas and added new thoughts and advice, both for readers already familiar with his work and for readers discovering it for the first time.", 18.99, 12, "MMM.jpg"),
("M*A*S*H - Season 7", "The complete season 7 of M*A*S*H on DVD", 19.79, 8, "mash7.jpg"),
("iPid", "Leave your mark on the screen", 499.99, 10, "ipid.jpg"),
("A Coat", "Men's fashion - pink coat. Size: Medium", 25.99, 2, "pinkcoat.jpg"),
("Bike Lights Set", "Front and rear lights for your bike - safety first", 15.99, 5, "bikelights.jpg"),
("43&quot; TV", "A Big-ass TV, do you really need one this big? Yes, you do.", 489.00, 7, "bigtv.jpg"),
("30m Ethernet Cable", "30m Cat5e Ethernet LAN Network Patch Cable with RJ45 connectors", 2.41, 50, "cable.jpg"),
("Canon 660D DSLR", "Entry level Canon DSLR", 350.95, 10, "canon660d.jpg"),
("Intel 3rd Generation i5 3580K CPU", "4 x 3.40GHz, Ivy Bridge, Socket 1155, 6Mb L3 Cache, Intel Turbo Boost Technology 2.0", 161.17, 10, "intelcpu.jpg"),
("Solafeet Foot Tanner", "Tan whilst you surf...the internet", 189.00, 1, "foottanner.jpg"),
("Album in parent","Random product", 1.22, 1, "noimage.jpg"),
("Amazing Drama, Deepest Child", "TV Drama in subcategory", 5.33, 1, "noimage.jpg"),
("Album in music sub","Album in music subcategory", 3.99, 6, "noimage.jpg");
 
 
INSERT INTO product_category(p_id, cat_id) VALUES
(1,1),(2,103),(3,44),(4,15),(5,54),(6,7),(8,47),(9,55),(10,46),(11,56),(12,36),(13,2),(14,92),(15,12);

INSERT INTO product_image(p_id, pi_url, pi_main_pic) VALUES
(1,"ubfastcomp.jpg",1),(2,"cutekitten.jpg",1),(3,"MMM.jpg",1),
(4,"mast7.jpg",1),(5,"ipid.jpg",1),(6,"pinkcoat.jpg",1),
(7,"bikelights.jpg", 1),(8,"bigtv.jpg",1),(9,"cable.jpg",1),
(10,"canon660d.jpg",1),(11,"intelcpu.jpg",1),(12,"foottanner.jpg",1);